### ISSUE TITLE
how to add instance 

### ISSUE THREAD

**Issue by sany98215** [yoannfleurydev/vscode-gitlab-merge-request-upvotes#7]
given i added an instance which is like "http://ip",
when open instance in tree viewer  
I got an error "getaddrinfo ENOTFOUND http"

I want to know how to config instance or how much limits ,thanks

**Comment by yoannfleurydev** [comment]
Hi, at the moment, the instance should be added without the `http://` as I enforce the usage of `https://` for security reasons. If you really need `http` let me know, I'll try to release a new version this week.

**Comment by sany98215** [comment]
Thanks . I need http,and i try to remove code https ，but i know nothing about ts.
wait for new commits :)

**Comment by yoannfleurydev** [comment]
Don't worry, I'm not myself a TS expert and my code is a probably bit crappy :smiley: 

I have not tested, but [per the documentation](https://docs.gitlab.com/ee/api/merge_requests.html#list-merge-requests), I'll say that GitLab >= 9.5 is supported. :slightly_smiling_face:

**Comment by yoannfleurydev** [comment]
A new version has been released (0.3.1) that should fix your issue, please let me know if you have another problem adding instance 🙂

**Comment by sany98215** [comment]
thanks . when i update the 0.3.1, i had to add new instance with "http://ip" ，when i expend the instance , i got an error `http 400 code`.
Perhaps , when open the instance ,can not get `projectid`.

**Comment by yoannfleurydev** [comment]
Can you let me know which GitLab version you are using ?

I installed a GitLab on my machine and add an instance which was like the following : `http://localhost:8080` and it did work. I'll try to test with an `http://IP` when I'll have some time :)

**Comment by sany98215** [comment]
The version is 10.8.1 21a8d61 .

**Comment by yoannfleurydev** [comment]
So, I just tried with an IP and I have no issue:

![image](https://user-images.githubusercontent.com/3920615/88460271-50425a80-ce9b-11ea-92e9-0af0d31a2739.png)

Can you try the following request with your correct IP and your correct `private-token` and tell me the result:

```sh
curl --request GET \
  --url 'http://IP_PORT/api/v4/merge_requests?scope=created_by_me&state=opened' \
  --header 'private-token: TOKEN'
```

**Comment by yoannfleurydev** [comment]
Any news on this issue?

**Comment by sany98215** [comment]
it's OK,thanks for help!

**Comment by yoannfleurydev** [comment]
Thanks for your answer. :)
